const PAYMENT_HISTORY_STATUS = {
  PAYMENT_DONE: "결제완료",
  PURCHASE_APPROVAL_DONE: "구매확정완료",
  RETURN_REFUND_DONE: "반품환불완료",
  PARTIAL_CANCEL: "부분취소",
  PURCHASE_CANCEL: "결제취소",
  CANCEL_DONE: "취소완료",
} as const;

type PAYMENT_HISTORY_STATUS =
  typeof PAYMENT_HISTORY_STATUS[keyof typeof PAYMENT_HISTORY_STATUS];

export default PAYMENT_HISTORY_STATUS;
